#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
#
# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_lucky_bonjour:
    path: /lucky/bonjour
    controller: App\Controller\LuckyController::hello
